n1=int(input('enter num 1:'))
n2=int(input('enter num 2:'))
print('addition of the given numberis-->',n1+n2)
print('subtraction of the given numberis-->',n1-n2)
print('multiplication of the given numberis-->',n1*n2)
print('division  of the given numberis-->',n1/n2)
print('division of the given numberis-->',n1//n2)
print('division of the given numberis-->',n1%n2)
print('power of the given numberis-->',n1**n2)